[fonts]
size = 18
family = "MonoLisa Variable"

[window]
# opacity = 0.8
decorations = "transparent"
# blur = true
macos-use-unified-titlebar = true
macos-use-shadow = true

[renderer]
filters = ["/Users/sghng/.config/rio/shaders/crt/newpixie-crt.slangp"]

theme = "gruvbox"
