# A basic configuration for markdownlint
$schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json

line-length:
  code_blocks: false
  tables: false
no-duplicate-heading:
  siblings_only: true
no-inline-html: false
